version: '3.9'

services:
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped

  api:
    build: .
    command: node dist/src/server.js
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - redis

  worker:
    build: .
    command: node dist/src/workers/email.worker.js
    env_file:
      - .env
    depends_on:
      - redis